### ISSUE TITLE
Compiling on Arch Linux 4.0

### ISSUE THREAD

**Issue by simonvizzini** [bits3rpent/rtl8812AU_8821AU_linux#1]
Continuing [#41 from here](https://github.com/abperiasamy/rtl8812AU_8821AU_linux/issues/41)

I just installed the 4.0 kernel on my Arch installation and cannot compile, here the make output:

```
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.0.0-1-ck/build M=/mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux  modules
make[1]: Entering directory '/usr/lib/modules/4.0.0-1-ck/build'
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_cmd.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_security.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_debug.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_io.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_ioctl_query.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_ioctl_set.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_ieee80211.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_mlme.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_mlme_ext.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_wlan_util.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_vht.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_pwrctrl.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_rf.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_recv.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_sta_mgt.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_ap.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_xmit.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_p2p.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_tdls.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_br_ext.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_iol.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/rtw_sreset.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/core/efuse/rtw_efuse.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/osdep_service.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/os_intfs.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/usb_intf.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/usb_ops_linux.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/ioctl_linux.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/xmit_linux.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/mlme_linux.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/recv_linux.o
  CC [M]  /mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/ioctl_cfg80211.o
scripts/Makefile.build:258: recipe for target '/mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux/os_dep/linux/ioctl_cfg80211.o' failed
Makefile:1394: recipe for target '_module_/mnt/shared/data/Downloads/rtl8812au/bitsserpent/rtl8812AU_8821AU_linux' failed
make[1]: Leaving directory '/usr/lib/modules/4.0.0-1-ck/build'
Makefile:1040: recipe for target 'modules' failed
```

**Comment by bits3rpent** [comment]
Show me output of made --debug=v

also, is the the mainstream Arch? Want to make a branch for each distro.

**Comment by bits3rpent** [comment]
make*

**Comment by simonvizzini** [comment]
Ok, let me boot the 4.0 kernel and I'll get the output. The 4.0 kernel I'm using is not from the official repos, it's a linux-ck patched kernel, from the AUR. The official, non ck patched 4.0 kernel is in testing repo, haven't tried that one yet, but I assume the compile result will be the same, since the ck is only "slightly" patched with a better CPU scheduler (BFS, brain fuck scheduler haha :)), it's supposed to give better desktop performance, it sounds nice so I wanted to give it a try. But I think it should not affect the compilation

**Comment by simonvizzini** [comment]
Here's the output. First, this is the output I redirected to a file: http://pastebin.com/8th4B0wc

But my terminal showed up more messages that were not written to the file. So I copy & pasted the terminal output to a second file: http://pastebin.com/1SXabgJw

**Comment by bits3rpent** [comment]
I think it is best to put it into one file :)
made --debug=v &> output.txt
that will put everything in there.

**Comment by simonvizzini** [comment]
Ah! that's good to know! because I have run many times into this problem :) I'm just a linux noob experimenting a bit.

**Comment by bits3rpent** [comment]
We all have to start somewhere and we all can learn something :)

**Comment by bits3rpent** [comment]
In your second paste, searching for "error" will show you the problem. I will get working on it in a bit.

**Comment by simonvizzini** [comment]
I see! C++ has always been black magic to me... I never could get any examples off the internet to compile whenever I wanted to learn a bit C++... so thanks a lot for your effort :) you're a lifesaver

**Comment by simonvizzini** [comment]
Hi @bits3rpent, I'm curious if you had a chance to take a look at compiling the driver on 4.0? No hurry from my side, just curious. I'm using the 3.9.5 kernel for now and won't update until then. If you need any help or anything, just let me know!

**Comment by bits3rpent** [comment]
@simonvizzini hey, going to work on this later tonight.

**Comment by simonvizzini** [comment]
@bits3rpent don't worry! Someone has already patched the driver to make it compile under 4.0!

It's this one: https://github.com/vsurrel/rtl8812au

This one also apparently gives better speed (mine is so slow), but my next problem is that this driver won't detect my Edimax USB Wifi :( Ah well, one problem fixed, the next one appears. Is this normal under Linux?? ;)

**Comment by bits3rpent** [comment]
@simonvizzini Yeah I tried to contact the guy to see the "performance" change he/she/(it) made. Sadly, no response. 4.0 kernel is super new, so you can understand why I am not in a huge rush to work on this yet. I will try to get 4.0 to work today, I am 78% Edimax USB wifi is supported in my driver.

Normal in Linux? No. In life? Yes. 

Best wishes!

**Comment by bits3rpent** [comment]
My main concern/focus is to fix performance issues, 5Ghz issues, support as many devices as possible, and simplify the setup/testing process to help users out. For example, I just recently fixed a debug issue and released a debug branch to identify issues.

**Comment by simonvizzini** [comment]
@bits3rpent I don't think he made any special performance related changes! Big difference is he has forked version 4.3.8 of the driver, while your fork is based on 4.2.2

He has both versions:
4.3.8 https://github.com/vsurrel/rtl8812au
4.2.2 https://github.com/vsurrel/rtl8812AU_8821AU_linux

His 4.0 kernel patch is based on this one: https://github.com/OpenELEC/OpenELEC.tv/tree/master/packages/linux-drivers/RTL8812AU/patches

And I absolutely understand that you are in no rush to get it working on 4.0 kernel. I think there is no distribution yet except Arch Linux that now has it as its default. Seems kind of crazy but oh well, I'll ride that wave :) I wasn't trying to rush you, just desperate to be ready for the 4.0 kernel update.

Anyway, I'll just buy a new wifi adapter because this one is making trouble since I bought it.

**Comment by simonvizzini** [comment]
I case you haven't seen this yet, I just discovered this repo: https://github.com/ulli-kroll/rtl8821au

He seems to be doing a lot of rewriting of the driver, I thought this may be useful for your own fixes and patches.

**Comment by simonvizzini** [comment]
And looks like I accidentally closed this issue earlier, but I guess we can keep it closed? Since this issue is pretty much only Arch specific.

**Comment by bits3rpent** [comment]
thanks @simonvizzini! Feel free to keep in contact with me. bits3rpent@plasmachameleon.com
